
services:
  web:
    build: .
    container_name: django-dev
    command: gunicorn AssSub.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app:z
    environment:
      - DEBUG=1
